apiVersion: training.eduk8s.io/v1alpha1
kind: Workshop
metadata:
  name: lab-jupyter-on-k8s-02
spec:
  vendor: eduk8s.io
  title: "Jupyter on Kubernetes #2"
  description: A workshop exploring use of operators to deploy Jupyter notebooks to Kubernetes
  url: https://github.com/jupyter-on-kubernetes/lab-jupyter-on-k8s-02
  content: github.com/jupyter-on-kubernetes/lab-jupyter-on-k8s-02
  duration: 30m
  session:
    budget: large
    applications:
      console:
        enabled: true
      terminal:
        enabled: true
        layout: split
  workshop:
    objects:
    - apiVersion: apiextensions.k8s.io/v1beta1
      kind: CustomResourceDefinition
      metadata:
        name: jupyternotebook.jupyter-on-kubernetes.test
      spec:
        scope: Cluster
        group: jupyter-on-kubernetes.test
        names:
          plural: jupyternotebooks
          singular: jupyternotebook
          kind: JupyterNotebook
        versions:
          - name: v1alpha1
            served: true
            storage: true
        validation:
          openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                serviceAccountName:
                  type: string
                resources:
                  type: object
                  properties:
                    requests:
                      type: object
                      properties:
                        memory:
                          type: string
                        storage:
                          type: string
                    limits:
                      type: object
                      properties:
                        memory:
                          type: string
                        storage:
                          type: string
            status:
              type: object
        additionalPrinterColumns:
        - name: URL
          type: string
          priority: 0
          description: URL for acessing the Jupyter notebook.
          JSONPath: .status.jupyternotebook.url
        - name: Password
          type: string
          priority: 0
          description: Password for accessing the Jupyter notebook.
          JSONPath: .status.jupyternotebook.password
