apiVersion: training.eduk8s.io/v1alpha1
kind: Workshop
metadata:
  name: lab-jupyter-on-k8s-02
spec:
  vendor: eduk8s.io
  title: "Jupyter on Kubernetes #2"
  description: A workshop exploring use of operators to deploy Jupyter notebooks to Kubernetes
  url: https://github.com/eduk8s-tests/lab-jupyter-on-k8s-02
  content: github.com/eduk8s-tests/lab-jupyter-on-k8s-02
  duration: 30m
  session:
    budget: large
    applications:
      console:
        enabled: true
      terminal:
        enabled: true
        layout: split
