apiVersion: v1
kind: Service
metadata:
  name: notebook
  labels:
    app: notebook
spec:
  type: ClusterIP
  selector:
    deployment: notebook
  ports:
  - name: 8888-tcp
    port: 8888
    protocol: TCP
    targetPort: 8888
