apiVersion: jupyter-on-kubernetes.test/v1alpha1
kind: JupyterNotebook
metadata:
  name: notebook
spec:
  notebook:
    interface: lab
  deployment:
    image: jupyter/minimal-notebook
    serviceAccountName: default
    resources:
      limits:
        memory: 512Mi
  storage:
    claimName: workspaces
    subPath: workspace-1
