apiVersion: v1
kind: ConfigMap
metadata:
  name: notebook
  labels:
    app: notebook
data:
  jupyter_notebook_config.json: |-
    {
      "NotebookApp": {
        "password": "sha1:9c2069f12451:2ce0e0fb5b5cfa44fe90e8f92f5b9153d988dbd2"
      }
    }
